ALTER SESSION SET CURRENT_SCHEMA = student_app;

CREATE TABLE specialties (
    specialty_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(20) NOT NULL UNIQUE,
    name VARCHAR2(200) NOT NULL
);

CREATE TABLE study_groups (
    group_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name VARCHAR2(30) NOT NULL UNIQUE,
    specialty_id NUMBER NOT NULL REFERENCES specialties(specialty_id)
);

CREATE TABLE students (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name VARCHAR2(100) NOT NULL,
    first_name VARCHAR2(100) NOT NULL,
    middle_name VARCHAR2(100),
    admission_year NUMBER(4) NOT NULL CHECK (admission_year BETWEEN 2000 AND 2100),
    study_form VARCHAR2(30) NOT NULL CHECK (study_form IN ('очная', 'очно-заочная', 'заочная')),
    group_id NUMBER NOT NULL REFERENCES study_groups(group_id)
);

CREATE TABLE disciplines (
    discipline_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL UNIQUE
);

CREATE TABLE curriculum (
    curriculum_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialty_id NUMBER NOT NULL REFERENCES specialties(specialty_id),
    discipline_id NUMBER NOT NULL REFERENCES disciplines(discipline_id),
    semester NUMBER NOT NULL CHECK (semester BETWEEN 1 AND 12),
    hours NUMBER NOT NULL CHECK (hours > 0),
    report_type VARCHAR2(20) NOT NULL CHECK (report_type IN ('экзамен', 'зачет')),
    CONSTRAINT uq_curriculum UNIQUE (specialty_id, discipline_id, semester)
);

CREATE TABLE grades (
    grade_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL REFERENCES students(student_id),
    discipline_id NUMBER NOT NULL REFERENCES disciplines(discipline_id),
    study_period VARCHAR2(30) NOT NULL,
    grade VARCHAR2(20) NOT NULL,
    CONSTRAINT uq_grade UNIQUE (student_id, discipline_id, study_period)
);

CREATE TABLE app_users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    password_hash VARCHAR2(300) NOT NULL,
    role VARCHAR2(30) NOT NULL CHECK (role IN ('academic', 'teacher'))
);

CREATE TABLE audit_log (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_type VARCHAR2(10) NOT NULL,
    entity_name VARCHAR2(40) NOT NULL,
    record_id VARCHAR2(100),
    username VARCHAR2(100),
    changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    old_values CLOB,
    new_values CLOB
);
